version: '2'
services:
  proxy:
    build: ./proxy
    links:
      - vitta-challenge-api
    ports:
      - "80:80"
    restart: always

  vitta-challenge-api:
    build: ./app
    restart: always
    volumes:
      - .:/src:rw
